name: Docker Build, Push, and Run

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t jeevanjames2000/sampledocker:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push jeevanjames2000/sampledocker:latest

      # Step 5: Pull the Docker image and run it
      - name: Run Docker container
        run: |
          docker pull jeevanjames2000/sampledocker:latest
          docker run -d -p 7000:7000 jeevanjames2000/sampledocker:latest
