name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Google Chat - Build Started
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "🚀 Docker Deployment started for *sampledocker*"}' \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t jeevanjames2000/sampledocker:${{ github.sha }} .
          docker tag jeevanjames2000/sampledocker:${{ github.sha }} jeevanjames2000/sampledocker:latest

      - name: Push Docker image
        run: |
          docker push jeevanjames2000/sampledocker:${{ github.sha }}
          docker push jeevanjames2000/sampledocker:latest

      - name: Notify Google Chat - Build Successful
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "✅ *sampledocker* built successfully!"}' \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"

      - name: Notify Google Chat - Build Failed
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "❌ *sampledocker* build failed!"}' \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"

  deploy:
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Notify Google Chat - Deployment Started
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "🚀 Docker Deployment started for *sampledocker*"}' \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"

      - name: Pull latest Docker image
        run: docker pull jeevanjames2000/sampledocker:latest

      - name: Stop and remove existing container
        run: |
          docker stop sampledocker || true
          docker rm sampledocker || true

      - name: Run updated container
        run: docker run -d -p 7000:7000 --name sampledocker jeevanjames2000/sampledocker:latest

      - name: Notify Google Chat - Deployment Successful
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "✅ *sampledocker* deployed successfully!"}' \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"

      - name: Notify Google Chat - Deployment Failed
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "❌ *sampledocker* deployment failed!"}' \
          "${{ secrets.GOOGLE_CHAT_WEBHOOK }}"
