name: Docker Build, Push, and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 3: Build the Docker image with a unique tag
      - name: Build Docker image
        run: |
          docker build --no-cache -t jeevanjames2000/sampledocker:${{ github.sha }} .
          docker tag jeevanjames2000/sampledocker:${{ github.sha }} jeevanjames2000/sampledocker:latest

      # Step 4: Push the Docker image
      - name: Push Docker image
        run: |
          docker push jeevanjames2000/sampledocker:${{ github.sha }}
          docker push jeevanjames2000/sampledocker:latest

      # Step 5: Pull and run the Docker container
      - name: Run Docker container
        run: |
          docker pull jeevanjames2000/sampledocker-server:latest
          docker run -d -p 7000:7000 jeevanjames2000/sampledocker:latest
