deploy:
  runs-on: self-hosted
  needs: build-and-push

  steps:
    - name: Pull latest Docker image
      run: docker pull jeevanjames2000/sampledocker:latest

    - name: Stop and remove existing container
      shell: pwsh # Use PowerShell instead of Bash
      run: |
        if (docker ps -q -f name=sampledocker) {
            docker stop sampledocker
        }
        if (docker ps -a -q -f name=sampledocker) {
            docker rm sampledocker
        }

    - name: Run updated container
      run: docker run -d -p 7000:7000 --name sampledocker jeevanjames2000/sampledocker:latest
